[package]
name = "get-vk"
version = "0.1.0"
license.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
clap = { workspace = true }
sp1-sdk = { workspace = true }
