[package]
name = "op-succinct-fees"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[[bin]]
name = "l1_fee_scalar"
path = "bin/l1_fee_scalar.rs"

[dependencies]
tokio = { workspace = true }


